spring:
  h2:
    console:
      enabled: true
      path: /h2-console  # The path to access the H2 console

  datasource:
    url: jdbc:h2:mem:testdb  # URL for the H2 database
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    driverClass: org.h2.driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

#application
application:
  name: shopcart

app:
  jwtSecret: ${jwt_secret_key}
  jwtCookie: ${jwt_cookie_name}
  jwtExpiration: 86400000 #token expiry time is 24 hrs.

#Server
server:
  port: 8080
  servlet:
    contextPath: /api